package com.lumora.baselineprofile

import androidx.profileinstaller.ProfileInstallReceiver

/**
 * Baseline profile generator for Lumora.
 * Baseline profiles improve app startup performance by pre-compiling
 * critical code paths during installation rather than at runtime.
 *
 * To generate:
 * 1. Connect a device running Android 13+
 * 2. Run: ./gradlew :baselineprofile:generateBaselineProfile
 * 3. Copy the generated profile to :app:src:main:baseline-prof.txt
 *
 * This class is referenced by the baseline profile module manifest
 * and triggers the profile installation on first launch.
 */
class BaselineProfileGenerator : ProfileInstallReceiver() {
    // Profile installation is handled by the parent receiver class
    // No additional implementation needed — the profile data is in
    // the baseline-prof.txt resource file generated by the build tool.
}
